### ISSUE TITLE
Invalid blob data for particular column

### ISSUE THREAD

**Issue by AdityaHegde** [marcboeker/go-duckdb#39] opened 2022-08-24 15:30 UTC
Hi,
I have a data source which loads and queries fine on duckdb CLI and the nodejs client : https://drive.google.com/file/d/1HaWhVs3Wy5_kFEBE41w9ewLyeTAjLSnC/view?usp=sharing

When i import using this binding go panics with address violation or invalid address. Here is the code I am using,
```
package main

import (
  "database/sql"
  "fmt"
  _ "github.com/marcboeker/go-duckdb"
)

func ParseRows(rows *sql.Rows) {
  columns, err := rows.Columns()
  if err != nil {
    fmt.Println(err.Error())
    return
  }

  count := len(columns)
  values := make([]interface{}, count)
  scanArgs := make([]interface{}, count)
  for i := range values {
    scanArgs[i] = &values[i]
  }

  for rows.Next() {
    err = rows.Scan(scanArgs...)
    if err != nil {
      fmt.Printf("Scan Error: %s\n", err)
    } else {
      fmt.Println(values)
    }
  }
  err = rows.Err()
  if err != nil {
    fmt.Printf("Error: %s\n", err)
  }
  defer rows.Close()
}

const TableName = "nyc311_reduced"
const SourceFile = "nyc311-reduced.parquet"

func main() {
  db, err := sql.Open("duckdb", "stage.db?access_mode=READ_WRITE")
  if err != nil {
    fmt.Println(err)
    return
  }

  res, err := db.Query("DROP TABLE " + TableName)
  res, err = db.Query("CREATE TABLE " + TableName + " AS SELECT * FROM '" + SourceFile + "'")
  if err != nil {
    fmt.Println(err)
  }
  res, err = db.Query("PRAGMA table_info(" + TableName + ")")
  if err != nil {
    fmt.Println(err)
    return
  }
  ParseRows(res)
}
```
The following applies to the PRAGMA query,
1. Panic happens for row index 31 (column 31 in the parquet).
2. It is always for the dflt_value column of the PRAGMA output.
3. When there is no panic PRAGMA returns garbage value for its default value.

The length as seen in row.scanBlob for this is sometime negative. Entries in `s.prefix` are all 0 sometimes. Feels like there is some cursor movement issue. Couldn't pinpoint if duckdb is passing it incorrectly or if there is an issue with cursor movement.

**Comment by marcboeker** [comment] 2022-08-24 16:16
I had a quick look at it but I could not reproduce this reliably. Sometimes I get the segfault immediately and sometimes it executes multiple times in a row. I need more time to debug this. There seems to be a single row, that produces the problem. If I limit the select from the parquet file to a single row, there is no segfault.

**Comment by marcboeker** [comment] 2022-08-25 21:16
I've done intensive research on this and I was able to pinpoint it to a strange behaviour in the `PRAGMA table_info(foo)` statement which returns weird values for the `dflt_column`. Let's see, what the maintainers say about the [issue](https://github.com/duckdb/duckdb/issues/4499).

**Comment by AdityaHegde** [comment] 2022-08-26 13:12
Interesting find. Thanks a lot for the in depth analysis!

**Comment by marcboeker** [comment] 2022-09-13 19:17
I think we can close this, as it has been fixed in DuckDB master and will be available with a new release of DuckDB or by compiling it from source.

**Closed by marcboeker** 2022-09-13 19:17 UTC
